// GENERATED by tools/ref_pow.py (Python hashlib, an independent implementation).
// Smallest nonce n >= 0 such that SHA-256(prefix + ":" + n) has >= bits leading zero bits.
// Provisional: B's docs/POW_SPEC.md vectors are authoritative once available.
export interface PowVector {
  prefix: string;
  bits: number;
  nonce: string;
}

export const POW_VECTORS: PowVector[] = [
  { prefix: 'vector-a', bits: 0, nonce: '0' },
  { prefix: 'vector-a', bits: 1, nonce: '1' },
  { prefix: 'vector-a', bits: 8, nonce: '201' },
  { prefix: 'vector-a', bits: 12, nonce: '1965' },
  { prefix: 'vector-a', bits: 16, nonce: '41986' },
  { prefix: 'fd1.evt_demo_01.3fa91c20.7', bits: 0, nonce: '0' },
  { prefix: 'fd1.evt_demo_01.3fa91c20.7', bits: 1, nonce: '1' },
  { prefix: 'fd1.evt_demo_01.3fa91c20.7', bits: 8, nonce: '92' },
  { prefix: 'fd1.evt_demo_01.3fa91c20.7', bits: 12, nonce: '14517' },
  { prefix: 'fd1.evt_demo_01.3fa91c20.7', bits: 16, nonce: '34947' },
  { prefix: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', bits: 0, nonce: '0' },
  { prefix: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', bits: 1, nonce: '3' },
  { prefix: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', bits: 8, nonce: '333' },
  { prefix: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', bits: 12, nonce: '2787' },
  { prefix: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', bits: 16, nonce: '19262' },
  { prefix: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', bits: 0, nonce: '0' },
  { prefix: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', bits: 1, nonce: '6' },
  { prefix: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', bits: 8, nonce: '102' },
  { prefix: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', bits: 12, nonce: '340' },
  { prefix: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', bits: 16, nonce: '101806' },
  { prefix: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', bits: 0, nonce: '0' },
  { prefix: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', bits: 1, nonce: '1' },
  { prefix: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', bits: 8, nonce: '392' },
  { prefix: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', bits: 12, nonce: '12480' },
  { prefix: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', bits: 16, nonce: '86312' },
  { prefix: 'fd1.7c1f5b0e-3d52-4b7a-9c61-0a4d8e2f6b13.0f6c1a22-77de-5b1e-a301-9d4e5a6b7c88.42', bits: 0, nonce: '0' },
  { prefix: 'fd1.7c1f5b0e-3d52-4b7a-9c61-0a4d8e2f6b13.0f6c1a22-77de-5b1e-a301-9d4e5a6b7c88.42', bits: 1, nonce: '0' },
  { prefix: 'fd1.7c1f5b0e-3d52-4b7a-9c61-0a4d8e2f6b13.0f6c1a22-77de-5b1e-a301-9d4e5a6b7c88.42', bits: 8, nonce: '75' },
  { prefix: 'fd1.7c1f5b0e-3d52-4b7a-9c61-0a4d8e2f6b13.0f6c1a22-77de-5b1e-a301-9d4e5a6b7c88.42', bits: 12, nonce: '4584' },
  { prefix: 'fd1.7c1f5b0e-3d52-4b7a-9c61-0a4d8e2f6b13.0f6c1a22-77de-5b1e-a301-9d4e5a6b7c88.42', bits: 16, nonce: '24530' },
  { prefix: 'vector-a', bits: 18, nonce: '503715' },
];
