import hashlib
import json
import random
import re
import time
import uuid
from pathlib import Path

import pytest
from app.defence.config_schema import PowLayer
from app.defence.pow import protocol
from app.defence.pow.adaptive import difficulty
from app.defence.pow.load import record_and_get

ROOT = Path(__file__).resolve().parents[2]
VECTORS = json.loads((ROOT / "docs" / "pow_vectors.json").read_text(encoding="utf-8"))
KEY = "k" * 40
E, U = uuid.UUID(int=1), uuid.UUID(int=2)
NOW = 1_800_000_000


def mint(**kw):
    args = dict(kind="p", event_id=E, user_id=U, exp=NOW + 60, bits=8, pow_ok=False)
    args.update(kw)
    return protocol.mint(KEY, **args)


# ------------------------------------------------------------------ the PoW rule itself
@pytest.mark.parametrize("v", VECTORS["rule_vectors"], ids=lambda v: f"{v['prefix'][:12]}-{v['bits']}")
def test_independent_rule_vectors(v):
    """Vectors generated by scripts/gen_pow_vectors.py (plain hashlib, integer maths)."""
    assert hashlib.sha256(f"{v['prefix']}:{v['nonce']}".encode()).hexdigest() == v["sha256"]
    assert protocol.solution_ok(v["prefix"], v["nonce"], v["bits"])
    n = int(v["nonce"])
    if n > 0:  # it is the SMALLEST: nothing below satisfies it
        assert not any(protocol.solution_ok(v["prefix"], str(i), v["bits"]) for i in range(n))
    assert protocol.solve(v["prefix"], v["bits"]) == v["nonce"]


def test_frontend_vectors_agree_with_the_backend():
    """Member D's solver vectors (from their own Python tool): cross-implementation check."""
    src = (ROOT.parent / "frontend" / "src" / "features" / "challenge" / "pow.vectors.ts")
    if not src.exists():
        pytest.skip("frontend not present next to Member_B_Pipeline")
    rows = re.findall(r"prefix: '([^']*)', bits: (\d+), nonce: '(\d+)'", src.read_text(encoding="utf-8"))
    assert len(rows) >= 25
    for prefix, bits, nonce in rows:
        assert protocol.solution_ok(prefix, nonce, int(bits)), (prefix, bits, nonce)
        if int(nonce) > 0:
            assert not protocol.solution_ok(prefix, str(int(nonce) - 1), int(bits))  # theirs is minimal too


def test_leading_zero_bits_matches_integer_arithmetic():
    rng = random.Random(5)
    for _ in range(500):
        d = bytes(rng.getrandbits(8) if rng.random() > 0.3 else 0 for _ in range(32))
        assert protocol.leading_zero_bits(d) == 256 - int.from_bytes(d, "big").bit_length()
    assert protocol.leading_zero_bits(bytes(32)) == 256
    assert protocol.leading_zero_bits(b"\x80" + bytes(31)) == 0
    assert protocol.leading_zero_bits(b"\x01" + bytes(31)) == 7


@pytest.mark.parametrize("bad", ["", " 12", "12 ", "1.5", "-1", "0x10", "١٢٣", "1" * 21, "abc", "12\n"])
def test_solution_format_is_strict(bad):
    assert not protocol.solution_ok("p", bad, 0)  # even a 0-bit puzzle rejects malformed input


def test_solution_length_bound_is_enforced_before_hashing():
    assert protocol.solution_ok("p", "0" * 20, 0)
    assert not protocol.solution_ok("p", "0" * 21, 0)


# -------------------------------------------------------------------------- token format
@pytest.mark.parametrize("t", VECTORS["token_vectors"]["tokens"], ids=lambda t: f"{t['kind']}{t['pow_ok']}-{t['bits']}")
def test_token_vectors(t):
    tv = VECTORS["token_vectors"]
    got = protocol.mint(tv["key"], t["kind"], uuid.UUID(tv["event_hex"]), uuid.UUID(tv["user_hex"]), t["exp"], t["bits"],
                        bool(t["pow_ok"]), nonce=t["nonce"])
    assert got == t["token"]
    status, tok = protocol.check(t["token"], tv["key"], uuid.UUID(tv["user_hex"]), uuid.UUID(tv["event_hex"]), 1_000_000_000)
    assert status is protocol.Status.OK and tok.bits == t["bits"] and tok.pow_ok == bool(t["pow_ok"])
    if "solution" in t:
        assert protocol.solution_ok(t["token"], t["solution"], t["bits"])


def test_token_shape_and_length():
    t = mint()
    assert re.fullmatch(r"fd1\.p0\.[0-9a-f]{32}\.[0-9a-f]{32}\.\d+\.\d+\.[0-9a-f]{16}\.[0-9a-f]{24}", t)
    assert 126 <= len(t) <= 130  # bounded prefix: documented in POW_SPEC.md


def test_round_trip_and_binding():
    t = mint()
    status, tok = protocol.check(t, KEY, U, E, NOW)
    assert status is protocol.Status.OK and (tok.kind, tok.bits, tok.exp, tok.pow_ok) == ("p", 8, NOW + 60, False)
    assert protocol.check(t, KEY, uuid.UUID(int=3), E, NOW)[0] is protocol.Status.WRONG_BINDING  # another user
    assert protocol.check(t, KEY, U, uuid.UUID(int=3), NOW)[0] is protocol.Status.WRONG_BINDING  # another event


def test_expiry_boundary():
    t = mint(exp=NOW)
    assert protocol.check(t, KEY, U, E, NOW)[0] is protocol.Status.OK
    assert protocol.check(t, KEY, U, E, NOW + 1)[0] is protocol.Status.EXPIRED


def test_challenges_are_unique_even_with_identical_inputs():
    assert len({mint() for _ in range(200)}) == 200


@pytest.mark.parametrize(
    "mutate",
    [
        lambda t: t.replace(".8.", ".0.", 1),  # lowering the difficulty
        lambda t: t.replace(".p0.", ".p1.", 1),  # claiming the PoW is done
        lambda t: t.replace(".p0.", ".c0.", 1),  # changing the kind
        lambda t: t[:-1] + ("0" if t[-1] != "0" else "1"),  # last MAC character
        lambda t: t.replace("fd1.", "fd2.", 1),
        lambda t: t + "0",
        lambda t: t[:-4],
        lambda t: "",
        lambda t: "garbage",
        lambda t: t.upper(),
    ],
)
def test_any_tampering_is_forged(mutate):
    assert protocol.check(mutate(mint()), KEY, U, E, NOW)[0] is protocol.Status.FORGED


def test_wrong_key_is_forged_and_comparison_is_constant_time_api():
    assert protocol.check(mint(), "other-key", U, E, NOW)[0] is protocol.Status.FORGED
    import inspect

    assert "compare_digest" in inspect.getsource(protocol.check)


def test_a_captcha_challenge_carries_a_signed_pow_ok_bit_that_cannot_be_flipped():
    c1 = mint(kind="c", bits=0, pow_ok=True)
    assert protocol.check(c1, KEY, U, E, NOW)[1].pow_ok is True
    flipped = c1.replace(".c1.", ".c0.", 1)
    assert protocol.check(flipped, KEY, U, E, NOW)[0] is protocol.Status.FORGED
    c0 = mint(kind="c", bits=0, pow_ok=False)
    assert protocol.check(c0.replace(".c0.", ".c1.", 1), KEY, U, E, NOW)[0] is protocol.Status.FORGED


def test_mint_validates_its_inputs():
    with pytest.raises(ValueError):
        protocol.mint(KEY, "x", E, U, NOW, 8)
    with pytest.raises(ValueError):
        protocol.mint(KEY, "p", E, U, NOW, 100)


def test_solving_what_was_minted():
    t = mint(bits=12)
    n = protocol.solve(t, 12)
    assert protocol.solution_ok(t, n, 12) and not protocol.solution_ok(t, n, 40)


def test_verification_is_cheap():
    t = mint(bits=8)
    n = protocol.solve(t, 8)
    start = time.perf_counter()
    for _ in range(2000):
        protocol.check(t, KEY, U, E, NOW)
        protocol.solution_ok(t, n, 8)
    per_call_us = (time.perf_counter() - start) / 2000 * 1e6
    assert per_call_us < 500, f"verification took {per_call_us:.0f} microseconds"  # one HMAC + one SHA-256


# ------------------------------------------------------------------------ adaptive difficulty
def test_difficulty_is_monotone_and_capped():
    cfg = PowLayer(base_bits=14, risk_bits_max=6, load_bits_max=2, max_bits=20)
    grid = [i / 20 for i in range(21)]
    for load in grid:
        bits = [difficulty(cfg, risk, load) for risk in grid]
        assert bits == sorted(bits)  # more risk never easier
    for risk in grid:
        bits = [difficulty(cfg, risk, load) for load in grid]
        assert bits == sorted(bits)  # more load never easier
    assert difficulty(cfg, 0, 0) == 14 and difficulty(cfg, 1, 1) == 20 and max(difficulty(cfg, 5, 5), 0) == 20


def test_difficulty_is_clamped_for_out_of_range_inputs():
    cfg = PowLayer()
    assert difficulty(cfg, -3, -3) == cfg.base_bits
    assert difficulty(cfg, 9, 9) == min(cfg.base_bits + cfg.risk_bits_max + cfg.load_bits_max, cfg.max_bits)


def test_difficulty_never_exceeds_max_bits():
    assert difficulty(PowLayer(base_bits=14, max_bits=15, risk_bits_max=6, load_bits_max=2), 1, 1) == 15


# ---------------------------------------------------------------------------------- load
async def test_load_estimate_counts_previous_second(redis_client):
    sec = 1_000_000
    for _ in range(50):
        await record_and_get(redis_client, "t", "ev", 100, now=sec - 1)  # traffic in the previous second
    load = await record_and_get(redis_client, "t", "ev", 100, now=sec)
    assert load == pytest.approx(0.5, abs=0.02)
    for _ in range(300):
        await record_and_get(redis_client, "t", "ev", 100, now=sec - 1)
    assert await record_and_get(redis_client, "t", "ev", 100, now=sec) == 1.0  # capped
    assert await record_and_get(redis_client, "t", "other-event", 100, now=sec) == 0.0  # per event


async def test_load_estimate_expires_and_survives_redis_failure():
    class Dead:
        def pipeline(self, **_):
            raise ConnectionError("down")

    assert await record_and_get(Dead(), "t", "ev", 100) == 0.0  # never blocks entry
